/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JCalendar;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Rant AA
 */
public class formRegistro extends javax.swing.JFrame {

    /**
     * Creates new form formRegistro
     */
    public formRegistro() {
        initComponents();
        //jdate.getJCalendar().setMaxDayCharacters(5); // sets today as minimum selectable date        
        txtDIA.setText(fechaActual);
        txtDIA.setEditable(false);
        /*
        Date date=new Date();
        Date date2=new Date();
        jday.getDayChooser().setMinSelectableDate(date);
        System.out.println("Date: "+date);*/
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        //Getting current date
        Calendar cal = Calendar.getInstance();
        //Displaying current date in the desired format
        System.out.println("Current Date: " + sdf.format(cal.getTime()));
        String viejodate = sdf.format(cal.getTime());
        diaHoy= cal;
        try {

            java.util.Date nuevodate = sdf.parse(viejodate);
            jday.setMinSelectableDate(nuevodate);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }

    }
    public String fechaActual = java.time.LocalDate.now().toString();
    public Calendar diaHoy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEscaneoCredencial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomregistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aperegistro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        carreraregistro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ncregistro = new javax.swing.JTextField();
        btnagregarest = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bntEscaneolibro = new javax.swing.JButton();
        btnagregarLibro = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tituloregistro = new javax.swing.JTextField();
        autorregistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editorialregistro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        isbnregistro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtanhioRegistroLibro = new javax.swing.JTextField();
        txtTotalRegistro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtExistenciaRegistro = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tituloregistro2 = new javax.swing.JTextField();
        autorregistro2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editorialregistro2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        isbnregistro2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtanhioRegistroLibro2 = new javax.swing.JTextField();
        txtTotalRegistro2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtExistenciaRegistro2 = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnEntregar = new javax.swing.JButton();
        txtDIA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jday = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEscaneoCredencial.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnEscaneoCredencial.setText("Escanear Credencial");
        jPanel1.add(btnEscaneoCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        nomregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jPanel1.add(nomregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        aperegistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jPanel1.add(aperegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Carrera:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        carreraregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jPanel1.add(carreraregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setText("N. Control:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        ncregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jPanel1.add(ncregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, -1));

        btnagregarest.setText("Agregar ");
        jPanel1.add(btnagregarest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 300));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntEscaneolibro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        bntEscaneolibro.setText("Escanear LibroQr");
        jPanel2.add(bntEscaneolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnagregarLibro.setText("Agregar Libro");
        jPanel2.add(btnagregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Titulo:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 30));

        tituloregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(tituloregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 110, -1));

        autorregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(autorregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 110, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Autor:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, 30));

        editorialregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(editorialregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 20));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Editorial:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel7.setText("ISBN:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 20));

        isbnregistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(isbnregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel9.setText("Año:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 20));

        txtanhioRegistroLibro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(txtanhioRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 20));

        txtTotalRegistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(txtTotalRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 20));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel16.setText("Total:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 20));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel17.setText("Existencia:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, 20));

        txtExistenciaRegistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel3.add(txtExistenciaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, 20));

        jTabbedPane1.addTab("Libro ", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jLabel11.setText("Titulo:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        tituloregistro2.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jPanel4.add(tituloregistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, 20));

        autorregistro2.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jPanel4.add(autorregistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, 20));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jLabel12.setText("Autor:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        editorialregistro2.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jPanel4.add(editorialregistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 20));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jLabel13.setText("Editorial:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jLabel14.setText("ISBN:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        isbnregistro2.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jPanel4.add(isbnregistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 20));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel18.setText("Año:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 20));

        txtanhioRegistroLibro2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel4.add(txtanhioRegistroLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, 20));

        txtTotalRegistro2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel4.add(txtTotalRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 20));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel19.setText("Total:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, 20));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel20.setText("Existencia:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, 20));

        txtExistenciaRegistro2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jPanel4.add(txtExistenciaRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 20));

        jTabbedPane1.addTab("+", jPanel4);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 300));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 300, 360));

        btnRegistro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnRegistro.setText("Registrar");
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 120, 50));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel10.setText("Apartado de Libros");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        btnEntregar.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        btnEntregar.setText("Entregar ");
        getContentPane().add(btnEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 140, 50));
        getContentPane().add(txtDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, -1));

        jLabel15.setText("HOY:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        getContentPane().add(jday, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField aperegistro;
    public javax.swing.JTextField autorregistro;
    public javax.swing.JTextField autorregistro2;
    public javax.swing.JButton bntEscaneolibro;
    public javax.swing.JButton btnEntregar;
    public javax.swing.JButton btnEscaneoCredencial;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JButton btnagregarLibro;
    public javax.swing.JButton btnagregarest;
    public javax.swing.JTextField carreraregistro;
    public javax.swing.JTextField editorialregistro;
    public javax.swing.JTextField editorialregistro2;
    public javax.swing.JTextField isbnregistro;
    public javax.swing.JTextField isbnregistro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public com.toedter.calendar.JCalendar jday;
    public javax.swing.JTextField ncregistro;
    public javax.swing.JTextField nomregistro;
    public javax.swing.JTextField tituloregistro;
    public javax.swing.JTextField tituloregistro2;
    public javax.swing.JTextField txtDIA;
    public javax.swing.JTextField txtExistenciaRegistro;
    public javax.swing.JTextField txtExistenciaRegistro2;
    public javax.swing.JTextField txtTotalRegistro;
    public javax.swing.JTextField txtTotalRegistro2;
    public javax.swing.JTextField txtanhioRegistroLibro;
    public javax.swing.JTextField txtanhioRegistroLibro2;
    // End of variables declaration//GEN-END:variables
}
