/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.Estudiante;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rant AA
 */
public class ListaEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form ListaEstudiantes
     */
    public ListaEstudiantes() {
        initComponents();
        inicio();
    }

    private void inicio() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jtEstudiante.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConnection();

            String sql = "SELECT numCon,Nombre,ApellidoP, ApellidoM,Tel,Correo,Carrera,Permiso FROM estudiante";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Numero de control");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido P");
            modelo.addColumn("Apellido M");
            modelo.addColumn("Telefono");
            modelo.addColumn("Correo");
            modelo.addColumn("Carrera");
            modelo.addColumn("Permiso");
            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
            Erro er = new Erro();
            er.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            er.getError(ex.toString());
            er.setVisible(true);
            er.setTitle("Ha ocurrido un error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstudiante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxBuscarPor_ListaEstudiantes = new javax.swing.JComboBox<>();
        txtBuscadoListaEstudiantes = new javax.swing.JTextField();
        btnElimLisEs = new javax.swing.JButton();
        btnBuscarListaEs = new javax.swing.JButton();
        bnModListaEs = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtEstudiante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 860, 350));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        jLabel1.setText("Listado de Estudiantes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        cbxBuscarPor_ListaEstudiantes.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        cbxBuscarPor_ListaEstudiantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Nombre", "Apellido Paterno", "Apellido Materno", "N. Control", "Correo", "N. Telefono", "Carrera" }));
        getContentPane().add(cbxBuscarPor_ListaEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 210, -1));

        txtBuscadoListaEstudiantes.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        getContentPane().add(txtBuscadoListaEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 260, -1));

        btnElimLisEs.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        btnElimLisEs.setText("Eliminar");
        getContentPane().add(btnElimLisEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, -1));

        btnBuscarListaEs.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        btnBuscarListaEs.setText("Buscar");
        btnBuscarListaEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarListaEsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarListaEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        bnModListaEs.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        bnModListaEs.setText("Modificar");
        getContentPane().add(bnModListaEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public  void Rellenado(ArrayList<Estudiante> Estudiosos) {
        DefaultTableModel dtf = new DefaultTableModel();
        dtf.addColumn("Numero de control");
        dtf.addColumn("Nombre");
        dtf.addColumn("Apellido P");
        dtf.addColumn("Apellido M");
        dtf.addColumn("Telefono");
        dtf.addColumn("Correo");
        dtf.addColumn("Carrera");
        dtf.addColumn("Permiso");
        for (int i = 0; i < Estudiosos.size(); i++) {
            String renglon[] = new String[8];
            System.out.println("Nombres: " + Estudiosos.get(i).getNomEs());
            renglon[0] = Estudiosos.get(i).getNc();
            renglon[1] = Estudiosos.get(i).getNomEs();
            renglon[2] = Estudiosos.get(i).getApp();
            renglon[3] = Estudiosos.get(i).getApm();
            renglon[4] = Estudiosos.get(i).getTel();
            renglon[5] = Estudiosos.get(i).getCarrera();
            renglon[6] = Estudiosos.get(i).getCorreo();
            if (Estudiosos.get(i).isPermiso()) {
                renglon[7] = "Disponible";
            } else {
                renglon[7] = "No disponible";
            }
            dtf.addRow(renglon);
           
        }
        jtEstudiante.setModel(dtf);
    }

    private void btnBuscarListaEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarListaEsActionPerformed


    }//GEN-LAST:event_btnBuscarListaEsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
inicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bnModListaEs;
    public javax.swing.JButton btnBuscarListaEs;
    public javax.swing.JButton btnElimLisEs;
    public javax.swing.JComboBox<String> cbxBuscarPor_ListaEstudiantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtEstudiante;
    public javax.swing.JTextField txtBuscadoListaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
