/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.Libro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rant AA
 */
public class ListaLibros extends javax.swing.JFrame {

    /**
     * Creates new form ListaLibros
     */
    public ListaLibros() {
        initComponents();
        inicio();
    }

    private void inicio() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jtLibros.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConnection();

            String sql = "SELECT ISBN,Titulo,Autor,Editorial,anho,total,existencia FROM libros";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            //modelo.addColumn("ID");
            modelo.addColumn("ISBN");
            modelo.addColumn("Titulo");
            modelo.addColumn("Autor");
            modelo.addColumn("Editorial");
            modelo.addColumn("Anho");
            modelo.addColumn("Total");
            modelo.addColumn("Existencia");

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtLibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxLisLibros = new javax.swing.JComboBox<>();
        btnBuscarLibroListado = new javax.swing.JButton();
        btnModificarLibroListado = new javax.swing.JButton();
        txtcampolibro = new javax.swing.JTextField();
        ElimListaLibros = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtLibros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 720, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Listado de libros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Buscar por:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cbxLisLibros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxLisLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "ISBN", "Titulo", "Autor", "Editorial", "Año", "Total", "Existencia" }));
        getContentPane().add(cbxLisLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, -1));

        btnBuscarLibroListado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarLibroListado.setText("Buscar");
        getContentPane().add(btnBuscarLibroListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        btnModificarLibroListado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificarLibroListado.setText("Modificar");
        getContentPane().add(btnModificarLibroListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 110, -1));

        txtcampolibro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtcampolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 150, 30));

        ElimListaLibros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ElimListaLibros.setText("Eliminar");
        getContentPane().add(ElimListaLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 100, 30));

        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicio();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void Rellenado(ArrayList<Libro> Estudiosos) {
        DefaultTableModel dtf = new DefaultTableModel();
        dtf.addColumn("ISBN");
        dtf.addColumn("Titulo");
        dtf.addColumn("Autor");
        dtf.addColumn("Editorial");
        dtf.addColumn("Anho");
        dtf.addColumn("Total");
        dtf.addColumn("Existencia");
        for (int i = 0; i < Estudiosos.size(); i++) {
            String renglon[] = new String[7];
            System.out.println("Nombres: " + Estudiosos.get(i).getTitulo());
            renglon[0] = Estudiosos.get(i).getIsbn();
            renglon[1] = Estudiosos.get(i).getTitulo();
            renglon[2] = Estudiosos.get(i).getAutor();
            renglon[3] = Estudiosos.get(i).getEditorial();
            renglon[4] = Estudiosos.get(i).getAnho();
            renglon[5] = String.valueOf(Estudiosos.get(i).getTotal());
            renglon[6] = String.valueOf(Estudiosos.get(i).getExistencia());
            
            dtf.addRow(renglon);

        }
        jtLibros.setModel(dtf);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ElimListaLibros;
    public javax.swing.JButton btnBuscarLibroListado;
    public javax.swing.JButton btnModificarLibroListado;
    public javax.swing.JComboBox<String> cbxLisLibros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtLibros;
    public javax.swing.JTextField txtcampolibro;
    // End of variables declaration//GEN-END:variables
}
