/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ConsultaEstudiante;
import Modelo.ConsultaVisita;
import Modelo.Estudiante;
import Modelo.Visita;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rant AA
 */
public class ListaVisitas extends javax.swing.JFrame {

    /**
     * Creates new form ListaVisitas
     */
    public ListaVisitas() throws SQLException, ParseException {
        initComponents();
        valid();
    }

    public void valid() throws SQLException, ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        System.out.println("Current Date: " + sdf.format(cal.getTime()));
        ConsultaVisita consv = new ConsultaVisita();
        ArrayList<Visita> vis = null;
        vis = consv.getTodasVisitas();
        DefaultTableModel dtf = new DefaultTableModel();
        ConsultaEstudiante conses = new ConsultaEstudiante();
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        Date date = new Date();
        System.out.println("Hora actual: " + dateFormat.format(date));
        String[] tit = {"Id Visita","Nombre ", "Apellido", "N. Control", "Especialidad", "Fecha", "Hora"};
        dtf.setColumnIdentifiers(tit);
        for (int i = 0; i < vis.size(); i++) {
            Estudiante es = conses.getEstudiantePorId(vis.get(i).getIdEstudiante());
            Object[] filas = new Object[7];
            filas[0]=vis.get(i).getIdVisita();
            filas[1] = es.getNomEs();
            filas[2] = es.getApp() + " " + es.getApm();
            filas[3] = es.getNc();
            filas[4] = es.getCarrera();
            filas[5] = vis.get(i).getFecha();
            System.out.println("Hora del vis " + vis.get(i).getHora());
            filas[6] = vis.get(i).getHora();
            dtf.addRow(filas);
        }
        jtVisitas.setModel(dtf);
    }

    public void Rellenar(ArrayList<Visita> vis) throws SQLException, ParseException {
        
        DefaultTableModel dtf = new DefaultTableModel();
        ConsultaEstudiante conses = new ConsultaEstudiante();
        
        String[] tit = {"Id Visita","Nombre ", "Apellido", "N. Control", "Especialidad", "Fecha", "Hora"};
        dtf.setColumnIdentifiers(tit);
        for (int i = 0; i < vis.size(); i++) {
            Estudiante es = conses.getEstudiantePorId(vis.get(i).getIdEstudiante());
            Object[] filas = new Object[7];
            filas[0]=vis.get(i).getIdVisita();
            filas[1] = es.getNomEs();
            filas[2] = es.getApp() + " " + es.getApm();
            filas[3] = es.getNc();
            filas[4] = es.getCarrera();
            filas[5] = vis.get(i).getFecha();
            System.out.println("Hora del vis " + vis.get(i).getHora());
            filas[6] = vis.get(i).getHora();
            dtf.addRow(filas);
        }
        jtVisitas.setModel(dtf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxbuscarpor = new javax.swing.JComboBox<>();
        txtVisita = new javax.swing.JTextField();
        btnBuscarVisita = new javax.swing.JButton();
        btnModVisitas = new javax.swing.JButton();
        btnElimVis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVisitas = new javax.swing.JTable();
        btnRefrescarVisitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setText("Buscar por:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        cbxbuscarpor.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        cbxbuscarpor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona>", "Fecha", "id Visita", "Nombre", "N. Control" }));
        getContentPane().add(cbxbuscarpor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 30));
        getContentPane().add(txtVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 180, 30));

        btnBuscarVisita.setText("Buscar");
        getContentPane().add(btnBuscarVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 80, 30));

        btnModVisitas.setText("Modificar");
        btnModVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModVisitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 80, 30));

        btnElimVis.setText("Eliminar");
        getContentPane().add(btnElimVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 90, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Control de Visitas CI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 440, 50));

        jtVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtVisitas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 750, 270));

        btnRefrescarVisitas.setText("Refrescar");
        getContentPane().add(btnRefrescarVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModVisitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModVisitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListaVisitas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListaVisitas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(ListaVisitas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarVisita;
    public javax.swing.JButton btnElimVis;
    public javax.swing.JButton btnModVisitas;
    public javax.swing.JButton btnRefrescarVisitas;
    public javax.swing.JComboBox<String> cbxbuscarpor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtVisitas;
    public javax.swing.JTextField txtVisita;
    // End of variables declaration//GEN-END:variables
}
