/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Rant AA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnApartado = new javax.swing.JButton();
        btnListaLibrosGral = new javax.swing.JButton();
        btnVisitas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCrudEs = new javax.swing.JButton();
        ControlEs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCrudLib = new javax.swing.JButton();
        ControlLib = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCrudReg = new javax.swing.JButton();
        ControlReg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnApartado.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnApartado.setText("Apartado / Entrega de Libros");
        jPanel6.add(btnApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnListaLibrosGral.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnListaLibrosGral.setText("Lista de Libros");
        btnListaLibrosGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLibrosGralActionPerformed(evt);
            }
        });
        jPanel6.add(btnListaLibrosGral, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        btnVisitas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnVisitas.setText("Visitas CI");
        jPanel6.add(btnVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 330));

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrudEs.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        btnCrudEs.setText("CRUD Estudiante");
        jPanel3.add(btnCrudEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        ControlEs.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        ControlEs.setText("Control Estudiantes/Listado");
        jPanel3.add(ControlEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel2.setText("Estudiantes");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 490, 90));

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel3.setText("Libros");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        btnCrudLib.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        btnCrudLib.setText("CRUD Libros");
        jPanel4.add(btnCrudLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        ControlLib.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        ControlLib.setText("Control Libros/Listado");
        jPanel4.add(ControlLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel4.setText("Registros");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        btnCrudReg.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        btnCrudReg.setText("CRUD Registros");
        jPanel5.add(btnCrudReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        ControlReg.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        ControlReg.setText("Control Registros/Listado");
        jPanel5.add(ControlReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 90));

        jTabbedPane1.addTab("Avanzado", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 520, 360));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biblioteca Electronica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 430, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaLibrosGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLibrosGralActionPerformed
        ListaLibrosGral ll = new ListaLibrosGral();
        ll.setVisible(true);
        
        
    }//GEN-LAST:event_btnListaLibrosGralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ControlEs;
    public javax.swing.JButton ControlLib;
    public javax.swing.JButton ControlReg;
    public javax.swing.JButton btnApartado;
    public javax.swing.JButton btnCrudEs;
    public javax.swing.JButton btnCrudLib;
    public javax.swing.JButton btnCrudReg;
    public javax.swing.JButton btnListaLibrosGral;
    public javax.swing.JButton btnVisitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
