/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.Estudiante;
import Modelo.ImagenMySQL;
import static java.awt.PageAttributes.MediaType.D;
import static javafx.scene.input.KeyCode.D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Rant AA
 */
public class ModEstudiante extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form ModEstudiante
     */
    public ModEstudiante() {
        initComponents();
    }

    public  void Mostrar(int id) throws IOException {
        PreparedStatement ps;
        ResultSet rs;
        Conexion objCon = new Conexion();

        try {
            Connection con = objCon.getConnection();
            ps = con.prepareStatement("SELECT QR FROM estudiante WHERE id=?");
            ps.setInt(1,id);
            rs = ps.executeQuery();

            BufferedImage buffimg = null;
            byte[] image = null;
            while (rs.next()) {
                image = rs.getBytes("QR");
                InputStream img = rs.getBinaryStream(1); // reading image as InputStream
                try {
                    buffimg = ImageIO.read(img);
                    ImagenMySQL imagen = new ImagenMySQL(jpImagen.getHeight(), jpImagen.getWidth(), buffimg);
                    jpImagen.add(imagen);
                    jpImagen.repaint();
                } catch (IOException ex) {
                    
                }
            }

            Image img = Toolkit.getDefaultToolkit().createImage(image);
            ImageIcon icon = new ImageIcon(img);
            lblImagen.setIcon(icon);

            rs.close();
        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtcontrolMod = new javax.swing.JTextField();
        txtnomMod = new javax.swing.JTextField();
        txtapp2Mod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtapmMod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttelMod = new javax.swing.JTextField();
        txtcorMod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtespMod = new javax.swing.JComboBox<>();
        txtsexMod = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbsiMod = new javax.swing.JRadioButton();
        rbnoMod = new javax.swing.JRadioButton();
        txtid = new javax.swing.JTextField();
        btnModificarMod = new javax.swing.JButton();
        jpImagen = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtcontrolMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtcontrolMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));

        txtnomMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtnomMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

        txtapp2Mod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtapp2Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapp2ModActionPerformed(evt);
            }
        });
        getContentPane().add(txtapp2Mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Apellido Paterno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtapmMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtapmMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 120, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Genero");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txttelMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txttelMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, -1));

        txtcorMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtcorMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 120, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Permiso");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        txtespMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Ing.Gestion", "Ing.Agronomia", "Ing.Informatica", "Ing.Industrial" }));
        txtespMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtespModActionPerformed(evt);
            }
        });
        getContentPane().add(txtespMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 110, 30));

        txtsexMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Masculino", "Femenino" }));
        getContentPane().add(txtsexMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Numero de control");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Apellido Materno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Correo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Especialidad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        buttonGroup1.add(rbsiMod);
        rbsiMod.setText("Si");
        getContentPane().add(rbsiMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        buttonGroup1.add(rbnoMod);
        rbnoMod.setText("No");
        getContentPane().add(rbnoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 60, -1));

        btnModificarMod.setText("Modificar");
        btnModificarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarModActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 100, 30));

        jpImagen.setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().add(jpImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 50, 50));

        jButton1.setText("Cambiar Foto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 130, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapp2ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapp2ModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapp2ModActionPerformed

    private void txtespModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtespModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtespModActionPerformed

    private void btnModificarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarModActionPerformed
        try {
            Estudiante es = new Estudiante();
            es.setNomEs(txtnomMod.getText());
            es.setApp(txtapp2Mod.getText());
            es.setApm(txtapmMod.getText());
            es.setNc(txtcontrolMod.getText());
            es.setTel(txttelMod.getText());
            es.setCorreo(txtcorMod.getText());
            es.setSex(txtsexMod.getSelectedItem().toString());
            es.setCarrera(txtespMod.getSelectedItem().toString());
            es.setId(Integer.parseInt(txtid.getText()));
            if (rbsiMod.isSelected()) {
                es.setPermiso(true);
            } else {
                es.setPermiso(false);
            }

            Modificar(es);
            JOptionPane.showMessageDialog(null, "Modificado correctamente");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarModActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PNG", "png");
        fc.setFileFilter(filtro);
        int seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fc.getSelectedFile();

            PreparedStatement ps;
            ResultSet rs;
            Conexion objCon = new Conexion();

            try {

                FileInputStream fis = new FileInputStream(fichero);

                Connection con = objCon.getConnection();
                ps = con.prepareStatement("UPDATE estudiante SET QR=?  WHERE id=?");
                //ps=con.prepareStatement("UPDATE estudiante SET numCon=?, Nombre=?, ApellidoP=?, ApellidoM=?, Tel=?, Correo=?, Genero=?, Carrera=? WHERE id=?");
                ps.setBinaryStream(1, fis, (int) fichero.length());
                int ine = Integer.parseInt(txtid.getText());
                ps.setInt(2, ine);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Imagen Guardada");
                Mostrar(Integer.parseInt(txtid.getText()));
            } catch (HeadlessException | FileNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Guardar Imagen");
                System.out.println(ex);
            } catch (IOException ex) {
                Logger.getLogger(ModEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean Modificar(Estudiante es) throws SQLException {
        //Connection con = null;
        Conexion conn = new Conexion();
        Connection con = conn.getConnection();
        try {

            ps = con.prepareStatement("UPDATE estudiante SET numCon=?,Nombre=?, ApellidoP=?, ApellidoM=?, Tel=?,Correo=?,Genero=?, Carrera=?,Permiso=? WHERE id=?");
            ps.setString(1, es.getNc());
            ps.setString(2, es.getNomEs());
            ps.setString(3, es.getApp());
            ps.setString(4, es.getApm());
            ps.setString(5, es.getTel());
            ps.setString(6, es.getCorreo());
            ps.setString(7, es.getSex());
            ps.setString(8, es.getCarrera());
            ps.setBoolean(9, es.isPermiso());
            ps.setInt(10, es.getId());
            ps.execute();
            return true;

        } catch (SQLException e) {
            System.out.println(e);
            Erro er = new Erro();
            er.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            er.getError(e.toString());
            er.setVisible(true);
            er.setTitle("Ha ocurrido un error!");
            return false;
        } finally {
            con.close();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificarMod;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JLabel lblImagen;
    public javax.swing.JRadioButton rbnoMod;
    public javax.swing.JRadioButton rbsiMod;
    public javax.swing.JTextField txtapmMod;
    public javax.swing.JTextField txtapp2Mod;
    public javax.swing.JTextField txtcontrolMod;
    public javax.swing.JTextField txtcorMod;
    public javax.swing.JComboBox<String> txtespMod;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtnomMod;
    public javax.swing.JComboBox<String> txtsexMod;
    public javax.swing.JTextField txttelMod;
    // End of variables declaration//GEN-END:variables
}
