/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.ImagenMySQL;
import Modelo.Libro;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rant AA
 */
public class ModLibro extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form ModLibro
     */
    public ModLibro() {
        initComponents();
        txtidlibro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txisbn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttotalLibro = new javax.swing.JTextField();
        txtExistenciaLibro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtidlibro = new javax.swing.JTextField();
        btnModificarLibro = new javax.swing.JButton();
        jpImagen = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Libro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 250, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtit.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(txtit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 220, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Autor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtau.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(txtau, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 220, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Año");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txa.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(txa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Editorial");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txed.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(txed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("ISBN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txisbn.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(txisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 220, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txttotalLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(txttotalLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 220, 30));

        txtExistenciaLibro.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        getContentPane().add(txtExistenciaLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Existencia");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));
        getContentPane().add(txtidlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, -1));

        btnModificarLibro.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        btnModificarLibro.setText("Modificar");
        btnModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 140, 40));
        getContentPane().add(jpImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 50, 40));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 180, 180));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cargar QR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLibroActionPerformed
        try {
            Libro es = new Libro();
            es.setId(Integer.parseInt(txtidlibro.getText()));
            es.setIsbn(txisbn.getText());
            es.setTitulo(txtit.getText());
            es.setAutor(txtau.getText());
            es.setEditorial(txed.getText());
            es.setAnho(txa.getText());
            es.setTotal(Integer.parseInt(txttotalLibro.getText()));
            es.setExistencia(Integer.parseInt(txtExistenciaLibro.getText()));
            Modificar(es);
            JOptionPane.showMessageDialog(null, "Modificado correctamente");
        } catch (Exception e) {
            System.out.println("Error "+e);
            System.out.println(e.getCause());
        }
    }//GEN-LAST:event_btnModificarLibroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PNG", "png");
        fc.setFileFilter(filtro);
        int seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fc.getSelectedFile();

            PreparedStatement ps;
            ResultSet rs;
            Conexion objCon = new Conexion();

            try {

                FileInputStream fis = new FileInputStream(fichero);

                Connection con = objCon.getConnection();
                ps = con.prepareStatement("UPDATE libros SET QR=?  WHERE id=?");
                //ps=con.prepareStatement("UPDATE estudiante SET numCon=?, Nombre=?, ApellidoP=?, ApellidoM=?, Tel=?, Correo=?, Genero=?, Carrera=? WHERE id=?");
                ps.setBinaryStream(1, fis, (int) fichero.length());
                int ine = Integer.parseInt(txtidlibro.getText());
                ps.setInt(2, ine);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Imagen Guardada");
                Mostrar(Integer.parseInt(txtidlibro.getText()));
            } catch (HeadlessException | FileNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Guardar Imagen");
                System.out.println(ex);
            } catch (IOException ex) {
                Logger.getLogger(ModEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public  void Mostrar(int id) throws IOException {
        PreparedStatement ps;
        ResultSet rs;
        Conexion objCon = new Conexion();

        try {
            Connection con = objCon.getConnection();
            ps = con.prepareStatement("SELECT QR FROM libros WHERE id=?");
            ps.setInt(1,id);
            rs = ps.executeQuery();

            BufferedImage buffimg = null;
            byte[] image = null;
            while (rs.next()) {
                image = rs.getBytes("QR");
                InputStream img = rs.getBinaryStream(1); // reading image as InputStream
                try {
                    buffimg = ImageIO.read(img);
                    ImagenMySQL imagen = new ImagenMySQL(jpImagen.getHeight(), jpImagen.getWidth(), buffimg);
                    jpImagen.add(imagen);
                    jpImagen.repaint();
                } catch (IOException ex) {
                    
                }
            }

            Image img = Toolkit.getDefaultToolkit().createImage(image);
            ImageIcon icon = new ImageIcon(img);
            lblImagen.setIcon(icon);

            rs.close();
        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }
    public boolean Modificar(Libro es) throws SQLException {
        //Connection con = null;
        Conexion conn = new Conexion();
        Connection con = conn.getConnection();
        try {

            ps = con.prepareStatement("UPDATE libros SET ISBN=?,Titulo=?, Autor=?, Editorial=?, anho=?,total=?,existencia=? WHERE id=?");
            ps.setString(1, es.getIsbn());
            ps.setString(2, es.getTitulo());
            ps.setString(3, es.getAutor());
            ps.setString(4, es.getEditorial());
            ps.setString(5, es.getAnho());
            ps.setInt(6, es.getTotal());
            ps.setInt(7, es.getExistencia());
            ps.setInt(8, es.getId());

            ps.execute();
            return true;

        } catch (SQLException e) {
            System.out.println(e);
            Erro er = new Erro();
            er.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            er.getError(e.toString());
            er.setVisible(true);
            er.setTitle("Ha ocurrido un error!");
            return false;
        } finally {
            con.close();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificarLibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JLabel lblImagen;
    public javax.swing.JTextField txa;
    public javax.swing.JTextField txed;
    public javax.swing.JTextField txisbn;
    public javax.swing.JTextField txtExistenciaLibro;
    public javax.swing.JTextField txtau;
    public javax.swing.JTextField txtidlibro;
    public javax.swing.JTextField txtit;
    public javax.swing.JTextField txttotalLibro;
    // End of variables declaration//GEN-END:variables
}
