/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ConsultaListaRegistros;
import Modelo.Registro;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rant AA
 */
public class ModRegistro extends javax.swing.JFrame {

    /**
     * Creates new form ModRegistro
     */
    public ModRegistro() {
        initComponents();
        txidRegistro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fped = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txides = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txidli = new javax.swing.JTextField();
        rbfalse = new javax.swing.JRadioButton();
        rbtrue = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        txidRegistro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modificar Registro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        fped.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(fped, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Entrega");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        fent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(fent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("id Estudiante");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txides.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txides, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        jLabel5.setText("id Libro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txidli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txidli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));

        buttonGroup1.add(rbfalse);
        rbfalse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbfalse.setText("Pendiente");
        getContentPane().add(rbfalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        buttonGroup1.add(rbtrue);
        rbtrue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtrue.setText("Entregado");
        getContentPane().add(rbtrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));
        getContentPane().add(txidRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        ConsultaListaRegistros conslisr = new ConsultaListaRegistros();
        Registro es = new Registro();
        
        es.setFechaentrega(fent.getText());
        System.out.println("Dentro del form Fecha entrega " + es.getFechaentrega());
        es.setFechapedido(fped.getText());
        es.setIdEstudiante(Integer.parseInt(txides.getText()));
        es.setIdLibro(Integer.parseInt(txidli.getText()));
        es.setIdRegistro(Integer.parseInt(txidRegistro.getText()));
        if (rbtrue.isSelected()) {
            es.setEstado(true);            
        }
        if (rbfalse.isSelected()) {
            es.setEstado(false);
        }
        try {
            conslisr.ModificarRegistro(es);
        } catch (SQLException ex) {
            Logger.getLogger(ModRegistro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ModRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField fent;
    public javax.swing.JTextField fped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton rbfalse;
    public javax.swing.JRadioButton rbtrue;
    public javax.swing.JTextField txidRegistro;
    public javax.swing.JTextField txides;
    public javax.swing.JTextField txidli;
    // End of variables declaration//GEN-END:variables
}
