/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Rant AA
 */
public class nuevoLibro extends javax.swing.JFrame {

    /**
     * Creates new form nuevoLibro
     */
    public nuevoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txa = new javax.swing.JTextField();
        btnBuscarLibro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txisbn = new javax.swing.JTextField();
        btnLimpiarLibro = new javax.swing.JButton();
        btnGuardarLibro = new javax.swing.JButton();
        btnModificarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        txtidlibro = new javax.swing.JTextField();
        btnListadoLibros = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txttotalLibro = new javax.swing.JTextField();
        txtExistenciaLibro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtit.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Autor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtau.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtau, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Año");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txa.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(txa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 220, -1));

        btnBuscarLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Editorial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txed.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(txed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 220, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("ISBN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txisbn.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(txisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 220, -1));

        btnLimpiarLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btnLimpiarLibro.setText("Limpiar");
        btnLimpiarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        btnGuardarLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnModificarLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btnModificarLibro.setText("Modificar");
        btnModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        btnEliminarLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btnEliminarLibro.setText("Eliminar");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));
        jPanel1.add(txtidlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        btnListadoLibros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnListadoLibros.setText("Listado");
        btnListadoLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnListadoLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txttotalLibro.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(txttotalLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 220, 30));

        txtExistenciaLibro.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jPanel1.add(txtExistenciaLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 220, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Existencia");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jTabbedPane1.addTab("Datos Bibliograficos", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 590, 440));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel8.setText("Control De Libros");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        /*try {
            String titulo, autor, edi, anho,isbn;
            titulo=txtit.getText();
            autor=txa.getText();
            edi=txed.getText();
            anho=txa.getText();
            isbn=txisbn.getText();
            Manejo man=new Manejo();
            if (man.buscarLib(isbn)) {
                JOptionPane.showMessageDialog(null, "Error, esa isbn ya se ha ingresado anteriormente");
            }else{
                Libro nuevo=new Libro(titulo, autor, anho, edi,isbn);            
                man.Alta(2, null, nuevo, null);
                QRGenerador q=new QRGenerador();
                q.QrLibro(nuevo, isbn);
                Ficha_Bibliografica ficha=new Ficha_Bibliografica();
                ficha.iniciador(nuevo, "C:\\Users\\Admin\\Pictures\\WOW\\Libros\\"+q.getRuta()+".png");
                ficha.setVisible(true);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
        }*/
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnLimpiarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarLibroActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnListadoLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoLibrosActionPerformed

    }//GEN-LAST:event_btnListadoLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarLibro;
    public javax.swing.JButton btnEliminarLibro;
    public javax.swing.JButton btnGuardarLibro;
    public javax.swing.JButton btnLimpiarLibro;
    public javax.swing.JButton btnListadoLibros;
    public javax.swing.JButton btnModificarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField txa;
    public javax.swing.JTextField txed;
    public javax.swing.JTextField txisbn;
    public javax.swing.JTextField txtExistenciaLibro;
    public javax.swing.JTextField txtau;
    public javax.swing.JTextField txtidlibro;
    public javax.swing.JTextField txtit;
    public javax.swing.JTextField txttotalLibro;
    // End of variables declaration//GEN-END:variables
}
