/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.ConsultaListaRegistros;
import Modelo.Registro;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.JOptionPane;

/**
 *
 * @author Rant AA
 */
public class RegistrosExcelPrueba extends javax.swing.JFrame {

    /**
     * Creates new form ReportesPrueba
     */
    public RegistrosExcelPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbanual = new javax.swing.JRadioButton();
        rbDia = new javax.swing.JRadioButton();
        rbMes = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txtcampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        conmbo = new javax.swing.JComboBox<>();
        rbsemestre = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbanual);
        rbanual.setText("Anual");
        getContentPane().add(rbanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        buttonGroup1.add(rbDia);
        rbDia.setText("Dia");
        getContentPane().add(rbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        buttonGroup1.add(rbMes);
        rbMes.setText("Mensual");
        getContentPane().add(rbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jButton1.setText("Imprimir Registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));
        getContentPane().add(txtcampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, -1));

        jLabel1.setText("Valor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        conmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona>", "Primer Semestre Enero-Junio", "Segundo Semestre Julio-Diciembre" }));
        getContentPane().add(conmbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, -1));

        buttonGroup1.add(rbsemestre);
        rbsemestre.setText("Semestral:");
        getContentPane().add(rbsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel2.setText("AAAA-mm-dd");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String texto = txtcampo.getText();
            ConsultaListaRegistros consre = new ConsultaListaRegistros();
            ArrayList<Registro> ar=null;
            if (rbDia.isSelected()) {
                System.out.println("Selecciona el dia");
                ar=consre.getRegistros(0, texto, 0);
            }
            if (rbMes.isSelected()) {
                /*SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                java.util.Date date = sdf.parse(texto);
                java.sql.Date sqlDate = new Date(date.getTime());
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                System.out.println("Año: " + cal.get(Calendar.MONTH));*/
               ar= consre.getRegistros(1, texto, 0);
            }
            if (rbanual.isSelected()) {
                ar=consre.getRegistros(2, texto, 0);
            }
            if (rbsemestre.isSelected()) {
                if (conmbo.getSelectedIndex()==0) {
                    JOptionPane.showMessageDialog(null, "Debes seleccionar un semestre valido");
                    conmbo.setRequestFocusEnabled(true);
                    
                }else{
                    if (conmbo.getSelectedIndex()==1) {
                      ar=  consre.getRegistros(3, texto, 0);
                    }else{
                      ar=  consre.getRegistros(3, texto, 1);
                    }
                }
                
            }
            for (int i = 0; i < ar.size(); i++) {
                System.out.println(ar.get(i).toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrosExcelPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrosExcelPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrosExcelPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrosExcelPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrosExcelPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> conmbo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbDia;
    private javax.swing.JRadioButton rbMes;
    private javax.swing.JRadioButton rbanual;
    private javax.swing.JRadioButton rbsemestre;
    private javax.swing.JTextField txtcampo;
    // End of variables declaration//GEN-END:variables
}
